server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KeerthiRam20/spring-cloud-config-server-db


        health:
          enabled: true
      name: config-server

management:
  endpoint:
    health:
      show-details: always

